# Generated by Django 5.0.2 on 2024-03-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('degree', models.CharField(choices=[('Master', 'Master'), ('Secondary', 'Secondary')], max_length=512)),
            ],
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Speciality',
        ),
    ]
