# Generated by Django 5.0.2 on 2024-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teacher_rename_course_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('specialities', models.ManyToManyField(to='courses.speciality')),
                ('teachers', models.ManyToManyField(to='courses.teacher')),
            ],
        ),
    ]
