# Generated by Django 5.0.2 on 2024-03-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Special',
        ),
    ]
